FORMAT: 1A
HOST: http://nodejsbackend/

# G8 Openbank IoT Day

API for the Node.js backend to implement

## Receipts Collection [/receipts]

### List All Receipts [GET]

This endpoint should be used by the Mobile App to get all receipts info

+ Response 200 (application/json)

        [
            {
                "id": "1",
                "entity_name": "Universidad Politecnica de Madrid",
                "entity_id": "3",
                "emited_at": "2015-08-05T08:40:51.620Z",
                "amount": "173.28",
                "bank_name": "Openbank",
                "bank_id": "2",
                "pdf_url": "http://foo.bar.com",
                "paid": false
            }
        ]

### Create a New Receipt [POST]

Used by the Entities to register new receipts or by the Mobile App when
using manual input mode. It takes a JSON object containing the receipt
info.

+ Request (application/json)

        {
            "entity_name": "Universidad Politecnica de Madrid",
            "entity_id": "1",
            "emited_at": "2015-08-05T08:40:51.620Z",
            "amount": "173.28",
            "bank_name": "Openbank",
            "bank_id": "2",
            "pdf_url": "http://foo.bar.com",
            "concept": "Tuition fees", 
            "paid": false
        }

+ Response 201 (application/json)

    + Headers

            Location: /receipts/2

    + Body

            {
                "id": "2",
                "entity_name": "Universidad Politecnica de Madrid",
                "entity_id": "1",
                "emited_at": "2015-08-05T08:40:51.620Z",
                "amount": "173.28",
                "bank_name": "Openbank",
                "bank_id": "2",
                "pdf_url": "http://foo.bar.com",
                "concept": "Tuition fees", 
                "paid": false
            }
            
## Receipts [/receipts/{receipt_id}]

### Read Receipt details [GET]

Used by the Mobile App to get details of a Receipt

+ Response 201 (application/json)

    + Body

            {
                "id": "2",
                "entity_name": "Universidad Politecnica de Madrid",
                "entity_id": "1",
                "emited_at": "2015-08-05T08:40:51.620Z",
                "amount": "173.28",
                "bank_name": "Openbank",
                "bank_id": "2",
                "pdf_url": "http://foo.bar.com",
                "concept": "Tuition fees", 
                "paid": false
            }

### Update Receipt [PUT]

Mark a receipt as paid, for example

+ Request (application/json)

        {
            "paid": true
        }

+ Response 201 (application/json)

    + Body

            {
                "id": "2",
                "entity_name": "Universidad Politecnica de Madrid",
                "entity_id": "1",
                "emited_at": "2015-08-05T08:40:51.620Z",
                "amount": "173.28",
                "bank_name": "Openbank",
                "bank_id": "2",
                "pdf_url": "http://foo.bar.com",
                "concept": "Tuition fees", 
                "paid": true
            }

### Delete Receipt [DELETE]

Remove a receipt (reject for example)


+ Response 201
